<?php
/**
 * @file
 * Code for the Policies, Procedures, and Forms feature.
 *
 *
 * NOTE: Conditional Fields' "field dependencies" are not imported via Features, and documentation to
 * create field dependencies programatically (i.e., on install) is not available. As such, they must
 * be created manually, as per the following:
 *
 * - File is visible when URL or Upload File has value "File".
 * - URL is visible when URL or Upload File has value "URL".
 *
 */

include_once 'policies_procedures_and_forms.features.inc';

/**
 * Implements hook_menu().
 */
function policies_procedures_and_forms_menu() {
  $items = array();
  $items['policies-procedures-forms'] = array(
    'title' => 'Policies, Procedures, and Forms',
    'page callback' => '_ppf_page',
    'access arguments' => array('view ppf'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function policies_procedures_and_forms_permission() {
  return array(
    'view ppf' => array(
      'title' => t('View Policies, Procedures, and Forms'),
    ),
  );
}

/*
 * Implements hook_theme().
 */
function policies_procedures_and_forms_theme($existing, $type, $theme, $path) {
  return array(
    'views_view_field__policies_procedures_and_forms__block__title' => array(
      'arguments' => array('view' => NULL, 'field' => NULL, 'row' => NULL, 'output' => NULL),
      'template' => 'views-view-field--policies-procedures-and-forms--block--title',
      'path' => drupal_get_path('module', 'policies_procedures_and_forms') . '/templates',
    ),
  );
}

/**
 * Custom page callback function, declared in hook_menu().
 */
function _ppf_page() {
  drupal_add_css('
  .views-row {
    margin: 10px 0;
  }', 'inline');
   $output = '';
  if (user_access('create policies_procedures_and_forms content')) {
    $output .= '<li><a href="/node/add/policies-procedures-and-forms">Upload more Policies, Procedures and Forms</a></li>';
  }
  if (user_access('edit any policies_procedures_and_forms content')) {
    $output .= '<li><a href="/policies-procedures-forms/edit">Administer existing Policies, Procedures and Forms</a></li>';
  }
  if ($output) {
    $output = '<ul>' . $output . '</ul>';
  }
  $output .= views_embed_view('policies_procedures_and_forms', 'block');
  return $output;
}
